export const REQUEST_MOVIES = 'REQUEST_MOVIES';
export const RECEIVED_MOVIES = 'RECEIVED_MOVIES';
export const INVALIDATE_MOVIES = 'INVALIDATE_MOVIES';

export const REQUEST_MOVIE_DETAIL = 'REQUEST_MOVIE_DETAIL';
export const RECEIVE_MOVIE_DETAIL = 'RECEIVE_MOVIE_DETAIL';
export const INVALIDATE_MOVIE_DETAIL = 'INVALIDATE_MOVIE_DETAIL';

export const REQUEST_MOVIE_ATITLES = 'REQUEST_MOVIE_ATITLES';
export const RECEIVE_MOVIE_ATITLES = 'RECEIVE_MOVIE_ATITLES';
export const INVALIDATE_MOVIE_ATITLES = 'INVALIDATE_MOVIE_ATITLES';

export const REQUEST_MOVIE_REVIEW = 'REQUEST_MOVIE_REVIEW';
export const RECEIVE_MOVIE_REVIEW = 'RECEIVE_MOVIE_REVIEW';
export const INVALIDATE_MOVIE_REVIEW = 'INVALIDATE_MOVIE_REVIEW';

export const REQUEST_MOVIE_CREW = 'REQUEST_MOVIE_CREW';
export const RECEIVE_MOVIE_CREW = 'RECEIVE_MOVIE_CREW';
export const INVALIDATE_MOVIE_CREW = 'INVALIDATE_MOVIE_CREW';
